### ISSUE TITLE
Typo and need more variables

### ISSUE THREAD

**Issue by saolex** [openbridge/ob_php-fpm#23]
Typo  ob_php-fpm/docker-entrypoint.sh
- 71        echo 'max_executionn_time=300'
+ 71       echo 'max_execution_time=300'
 
Need more variables in .env file.
71        echo 'max_execution_time=300'
82        echo 'upload_max_filesize=50M'
83        echo 'post_max_size=50M'

**Comment by tspicer** [comment]
Hi, thanks for the note. Fixed the typo. If you want to extend with more variables, feel free to make a  PR with the changes.
