### ISSUE TITLE
ALERT: oops, unknown child

### ISSUE THREAD

**Issue by molepage** [openbridge/ob_php-fpm#38]
Hi,

I'm seeing a few of these errors in the logs, haven't been able to tie them to anything specific.  Just wondering if it rings a bell and what might be wrong.  Running WP.  Thanks!

ALERT: oops, unknown child (31184) exited with code 1. Please open a bug report (https://bugs.php.net).

**Comment by tspicer** [comment]
This bug it seems has been open for a long time: https://bugs.php.net/bug.php?id=73342

I don't think it is impacting the service

**Comment by molepage** [comment]
In that thread I'm seeing #73342 fixed since 7.1.20: [release log](http://git.php.net/?p=php-src.git;a=blob;f=NEWS;h=c0e391cb6e246a03c7ba8a840a662fb67a6950c3;hb=69dee5c732fe982c82edb17d0dbc3e79a47748d8)

`- FPM:
   9   . Fixed bug #73342 (Vulnerability in php-fpm by changing stdin to
  10     non-blocking). (Nikita)`

I saw these errors on 7.3 and 7.4, so maybe not the same issue?

Anyhow, I didn't see an impact on service either, but mine is a lightweight deployment.

**Comment by tspicer** [comment]
I can't really say the cause of this alert other than you can find cases where this has popped up in various forums. It might be marked as "fixed" but nothing says a regression can not be introduced either. It might also be a related, but different issue. The install is straightforward and any resolution likely would need to occur upstream.

BTW, how much ram do you have on your host?

**Comment by molepage** [comment]
Indeed.  Closing since it answers my initial question of "does it ring a bell?" and is outside the scope of this repo.  Thanks!

4GB on a KVM
